hashicorp/terraform-provider-nomad

README.md, nomad/provider.go, nomad/provider_test.go, nomad/resource_job_test.go, vendor/github.com/hashicorp/nomad/api/acl.go, vendor/github.com/hashicorp/nomad/api/agent.go, vendor/github.com/hashicorp/nomad/api/allocations.go, vendor/github.com/hashicorp/nomad/api/api.go, vendor/github.com/hashicorp/nomad/api/contexts/contexts.go, vendor/github.com/hashicorp/nomad/api/deployments.go, vendor/github.com/hashicorp/nomad/api/evaluations.go, vendor/github.com/hashicorp/nomad/api/fs.go, vendor/github.com/hashicorp/nomad/api/jobs.go, vendor/github.com/hashicorp/nomad/api/jobs_testing.go, vendor/github.com/hashicorp/nomad/api/namespace.go, vendor/github.com/hashicorp/nomad/api/nodes.go, vendor/github.com/hashicorp/nomad/api/operator.go, vendor/github.com/hashicorp/nomad/api/quota.go, vendor/github.com/hashicorp/nomad/api/search.go, vendor/github.com/hashicorp/nomad/api/sentinel.go, vendor/github.com/hashicorp/nomad/api/system.go, vendor/github.com/hashicorp/nomad/api/tasks.go, vendor/github.com/hashicorp/nomad/helper/uuid/uuid.go, vendor/github.com/hashicorp/nomad/helper/uuid/uuid_test.go, vendor/vendor.json
acctest was failing even before the changes, first commit fixes that (in the easiest way I could figure out)
nomad api had to updated to 0.7.0 for this.
It's basically `govendor fetch ...@=v0.7.0`
=> Add support for ACL secret_id

nomad/resource_job_test.go
Nomad 0.7.1 had an accidental backwards compatibility break and
increased the minimum CPU allocation allowed in the job spec. What was
previously 20 is now 100. This was reported at hashicorp/nomad#3709.
This breaks our tests, which had a CPU allocation of 20. This PR just
increases them to 100, which allows the tests to pass again.
A fix (hashicorp/nomad#3706) has been merged, and will be part of the
next release, but I think it's worthwhile to change our tests and avoid
contributors stumbling into this on their own when running against
0.7.1, even if it'll work again in the next version of Nomad.
=> Increase the test job's cpu.

nomad/provider.go, nomad/resource_acl_token.go, nomad/resource_acl_token_test.go, website/docs/r/acl_token.html.markdown, website/nomad.erb
Allow Terraform to declaratively manage Nomad ACL tokens.
=> Implement an acl_token resource.

nomad/provider.go, nomad/resource_acl_policy.go, nomad/resource_acl_policy_test.go, website/docs/r/acl_policy.html.markdown, website/nomad.erb
Add a new resource that enables the management of ACL policies. It
allows declaratively defining an ACL policy, and Terraform will make
sure it exists in the Nomad cluster.
=> Add a resource for managing ACL policies.

nomad/data_source_regions.go, nomad/resource_acl_policy_test.go, nomad/resource_acl_token_test.go, nomad/resource_namespace.go, nomad/resource_namespace_test.go, nomad/resource_quota_specification.go, nomad/resource_quota_specification_test.go, nomad/resource_sentinel_policy.go, nomad/resource_sentinel_policy_test.go, vendor/github.com/hashicorp/nomad/helper/funcs.go, vendor/github.com/hashicorp/nomad/jobspec/parse.go, vendor/vendor.json
With the push for 1.2, we had a bunch of stuff happening in parallel,
that made some issues when they all landed. Notably, we changed the type
being returned by ProviderConfig, which made every use of meta that
wasn't updated panic. All the uses that were merged at the time were
updated, but the ones in flight when the PR was opened were not, causing
them to panic. This PR fixes that.
The vendor for `jobspec` from Nomad was also updated, as it didn't have
a field for namespace at the time it was vendored, which means that jobs
could not be scheduled in namespaces. Now they can.
All tests now pass:
```
make testacc TEST=./nomad
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./nomad -v  -timeout 120m
=== RUN   TestDataSourceRegions
--- PASS: …
```
=> Fix up in-flight errors for 1.2.

nomad/resource_job.go, nomad/resource_job_test.go, website/docs/r/job.html.markdown
This will allow using the nomad provider with json built jobspecs.
Example can be found in the tests.
=> Enable json jobs as jobpecs

website/docs/r/namespace.html.markdown
I discovered that one can specify a resource quota when creating a namespace with this resource.  For instance:
```
resource "nomad_quota_specification" "dev" {
name = "dev"
description = "dev quota"
limits {
region = "global"
region_limit {
cpu = 4600
memory_mb = 4096
}
}
}
resource "nomad_namespace" "dev" {
name = "dev"
quota = "${nomad_quota_specification.dev.name}"
description = "Shared development environment."
}
```
=> Add quota argument to namespace resource

nomad/resource_job.go, scripts/stop-nomad.sh, vendor/modules.txt, website/docs/r/job.html.markdown
Resolves #56 
This PR adds the option for the Nomad TF provider to monitor the deployment on job create/update, until such time as it completes or fails. This requires that a deployment is created, which requires that the job have an `update` stanza.
=> Monitor job after registration until deployment is complete

CHANGELOG.md, nomad/data_source_deployments_test.go, nomad/datasource_nomad_job.go, nomad/datasource_nomad_job_test.go, nomad/resource_job.go, nomad/resource_job_test.go, nomad/resource_namespace.go, scripts/start-nomad.sh
improves the support for Nomad namespaces
* job datasource takes a namespace field
* job datasource and resources have a `namespace` attribute now
* namespace deletion will retry loop to give jobs a chance to be stopped
* more testing
* changing the namespace on a job will result in a new resource being created and the old being deleted
resolves #69
=> support namespaces for nomad jobs

nomad/resource_namespace.go, nomad/resource_namespace_test.go, website/docs/r/namespace.html.markdown
Currently if you reference the `default` namespace in your configuration Terraform will fail to destroy it because the API will return a 500 error:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy
Terraform will perform the following actions:
- resource "nomad_namespace" "default" {
- description = "Default shared namespace" -> null
- id          = "default" -> null
- name        = "default" -> null
}
Plan: 0 to add, 0 to change, 1 to destroy.
Do you want to perform these actions?
Terraform will perform the actions described above.
Only 'yes' will be accepted to approve.
Enter a value: yes
nomad_namespace.default: Destroying... [id=default]
Error: error deleting namespace "default": Unexpected response code: …
```
=> Fix delete default namespace

nomad/resource_job.go, nomad/resource_job_test.go
In some workflows the Nomad server may not be available during the planning phase of Terraform (such as when the server is deployed by Terraform as well).
This PR replaces the error with a warning log message so `terraform apply` can start successfully.
Fixes #66.
=> Prevent error if Nomad server is not available during plan phase

nomad/datasource_nomad_job_test.go, nomad/resource_job_test.go
This PR adds explicit tests for `auto_promote` support in the Job resource and data source.
For the data source the job type had to be changed from `batch` to `service` to allow the addition of the `update` stanza.
Closes #68
=> add `auto_promote` key on job tests

go.mod, go.sum, nomad/core/README.md, nomad/core/jobspec/parse_group.go, nomad/core/jobspec/parse_service.go, nomad/resource_job.go, nomad/resource_job_test.go, vendor/github.com/hashicorp/nomad/api/services.go, vendor/github.com/hashicorp/nomad/api/tasks.go, vendor/modules.txt
Nomad [v0.10.0-rc.1](https://github.com/hashicorp/nomad/releases/tag/v0.10.0-rc1) has been released. 
This PR updates the Nomad API version and other Nomad dependencies to support the new features available in this new version.
=> Support Nomad v0.10.0-rc.1

CHANGELOG.md, nomad/resource_job.go, nomad/resource_job_test.go, vendor/github.com/stretchr/testify/require/doc.go, vendor/github.com/stretchr/testify/require/forward_requirements.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require.go.tmpl, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/github.com/stretchr/testify/require/require_forward.go.tmpl, vendor/github.com/stretchr/testify/require/requirements.go, vendor/modules.txt
the schema for nomad_job resources include TaskGroup.Volumes as a list, because the TF 0.12 SDK doesn't currently support maps with non-primitive values.
however, the Nomad API doesn't return a map with consistently ordered elements. as a result, simply looping over the map values to make a list results in potentially inconsistent list.
this PR sorts the entries of the list by Volume name, so that they are consistently ordered.
this resolves #93
=> sort TaskGroup.Volumes when converting to list

CHANGELOG.md, go.mod, go.sum, nomad/core/jobspec/parse.go, nomad/core/jobspec/parse_group.go, nomad/core/jobspec/parse_network.go, nomad/core/jobspec/parse_service.go, nomad/core/jobspec/parse_task.go, nomad/resource_job_test.go, vendor/github.com/hashicorp/nomad/api/agent.go, vendor/github.com/hashicorp/nomad/api/allocations.go, vendor/github.com/hashicorp/nomad/api/api.go, vendor/github.com/hashicorp/nomad/api/constraint.go, vendor/github.com/hashicorp/nomad/api/fs.go, vendor/github.com/hashicorp/nomad/api/go.mod, vendor/github.com/hashicorp/nomad/api/go.sum, vendor/github.com/hashicorp/nomad/api/jobs.go, vendor/github.com/hashicorp/nomad/api/nodes.go, vendor/github.com/hashicorp/nomad/api/services.go, vendor/github.com/hashicorp/nomad/api/tasks.go, vendor/modules.txt
updated parsing and API objects. specifically, adds support for: 
* sidecar_service -> tags
* volume_mount -> propagation_mode
resolves #93
=> updated nomad API to 0.10.3

website/docs/index.html.markdown
As illustrated by #112, it's not obvious how to work multi-region clusters. This PR explains how to use `alias` to accomplish that.
=> Explain how to use alias for multi-region clusters

go.mod, go.sum
`diff -r` showed no changes to the jobspec parsing
=> deps: updated nomad api client to 0.11.3

CHANGELOG.md
the changelog entry indicated support for API 0.11.2, but i moved it to 0.11.3 before the release (as suggested by the PR description and verified by the commit SHA in the PR)
=> error in changelog description

nomad/resource_job.go, nomad/resource_job_test.go, website/docs/r/job.html.markdown
Closes https://github.com/terraform-providers/terraform-provider-nomad/issues/124
=> Add purge_on_delete to nomad_job resource

CHANGELOG.md, nomad/resource_job.go, nomad/resource_job_test.go, website/docs/r/job.html.markdown
"delete" does not adhere to either nomad or terraform nomenclature; terraform uses "destroy" for resources, while nomad uses "deregister" for jobs. this is an update to #127 to rename this (which I didn't notice during the PR)
cc: @remilapeyre
=> renamed nomad_job purge_on_delete to purge_on_destroy

.travis.yml, nomad/data_source_namespace_test.go
modified the travis setup to stop using `make localtestacc`, which was eating any test errors 🤦 
commit 4626dea modifies a test to fail; with the modifications in cd314f7, this fails the build: 
https://travis-ci.org/github/terraform-providers/terraform-provider-nomad/builds/715654929
commit 86f2b24 undoes the failure and passes.
=> refactor travis testing to not eat failed tests

.travis.yml, GNUmakefile
The docs are now live in https://registry.terraform.io/providers/hashicorp/nomad, so we don't need this target anymore.
=> Remove `make website-test`

nomad/resource_volume.go, website/docs/r/volume.html.markdown
=> resource/volume: add "mount_options" argument to volume resource.

nomad/data_source_datacenters.go, nomad/data_source_datacenters_test.go, nomad/provider.go, website/docs/d/datacenters.html.md, website/nomad.erb
This PR introduces a new data source to list datacenters in the region where the provider is configured.
```hcl
data "nomad_datacenters" "datacenters" {
prefix            = "prod"
ignore_down_nodes = true
}
```
An [alias](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations) can be used for listing datacenters in multiple regions.
Closes #151
=> Add data source for listing datacenters

nomad/resource_volume.go
When registering a volume in a specific namespace, the provider would fail with the error:
```
Error: Provider produced inconsistent result after apply
When applying changes to nomad_volume.ebs, provider
"registry.terraform.io/hashicorp/nomad" produced an unexpected new value: Root
resource was present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
This happened because the registration action was not setting the namespace in the request, but the read (and delete) do, so the volume would 404 on read and the state would be inconsistent.
=> Fix issue where volume register would not set namespace

go.mod, nomad/data_source_scheduler_config.go, nomad/data_source_scheduler_config_test.go, nomad/provider.go, website/docs/d/scheduler_config.html.md, website/nomad.erb
There are no tests, because they unfortunately clash with the scheduler config resource, which updates the config values meaning the datasource tests have a race condition output with that. I'll think how to better approach this, but it highlights why this resource should be used carefully.
The dependancy update is unrelated to this change, but is needed as a result of 438a0b8 so is included.
=> datasource: add Nomad scheduler config data source.

website/docs/r/namespace.html.markdown
remove Ent/OSS warning about namespace resource now that namespaces are available in OSS Nomad
resolves #176
=> remove ENT warning

nomad/resource_job.go, nomad/resource_job_test.go, website/docs/r/job.html.markdown
Fix https://github.com/hashicorp/terraform-provider-nomad/issues/179
=> Support HCL2 on nomad Go package

nomad/provider.go, website/docs/index.html.markdown
This change adds a number of new provider config params that allow users to configure TLS certificates via strings, alongside the pre-existing file location method.
The provider schema ConflictsWith param is used to notify users when a configuration attempts to use two keys which affect the same TLS config param. In order to successfully use this, the existing DefaultFunc default values have been moved from an empty string to nil. This is because Terraform treats an empty string var as being populated, and therefore raises a conflict error whenever a new param is set. I tested this change locally to ensure it didn't cause any compatibility issues, and didn't find any. It is reassures that the Consul provider went through the same change.
The provider doesn't have much testing around its …
=> provider: support TLS certs configured by strings.

nomad/resource_volume.go, website/docs/r/volume.html.markdown
The `nomad_volume` resource had `mount_options` as a map with complex types, which Terraform can't process properly. The Nomad API also redacts `mount_options` from its response since it may contain sensitive values.
This PR changes the field type to a list with only 1 item to allow passing the sub-fields from the config file. It also doesn't try to read back `mount_options` from the API since it will always be `nil`.
Since the schema was modified, a migration function was necessary. 
Fixes #182
=> Fix `mount_options` in `nomad_volume` 

scripts/getconsul.sh, scripts/getnomad.sh, scripts/getvault.sh
The HCL2 tests target Nomad 1.0.0+, so they weren't running on CI.
=> ci: update hashistack deps

website/docs/r/job.html.markdown
Hello maintainers 👋🏼 
Just a small fix to the docs for the `nomad_job` resource.
=> fixes a typo in the job spec

nomad/resource_job.go, nomad/resource_job_test.go, website/docs/r/job.html.markdown
Add new attribute to the `hcl2` field in the `nomad_job` resource to allow passing extra HCL2 variable values.
Docs preview:
Closes #195
=> Allow passing HCL2 variables to job

go.mod, go.sum, nomad/provider_test.go, nomad/resource_job_test.go, nomad/resource_namespace_test.go, scripts/getnomad.sh
* set nomad parsing to 1.0.4 (was accidentally set to `HEAD` by previous PR)
* added tests for 1.0.4 features (terminating connect gateways)
* some general testing cleanup
=> parsing to 1.0.4, testing changes

.travis.yml
The `trusty` environment hit EOL, which was causing test to fail. Also updates YAML formatting.
=> Update TravisCI base OS

nomad/resource_job.go, website/docs/r/job.html.markdown
[Timeouts](https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts) were not being declared in the resource schema, so it was not possible to customize them.
Closes #210
=> Add timeout config to nomad_job resource

go.mod, go.sum, nomad/provider.go, nomad/resource_external_volume.go, nomad/resource_volume.go, website/docs/r/external_volume.html.markdown, website/nomad.erb
Add a new resource, `nomad_external_volume` to use the new CSI capability in Nomad 1.1.0 to create and register external volumes through Nomad.
Also update the existing `nomad_volume` resource to [deprecate fields](https://www.nomadproject.io/docs/upgrade/upgrade-specific#csi-volumes), following the [official guidelines](https://www.terraform.io/docs/extend/best-practices/deprecations.html#renaming-a-required-attribute).
Closes #208
=> Add new CSI volume capabilities

nomad/datasource_nomad_plugin.go
I was having an issue using `nomad_external_volume` with the following snippet:
```hcl
resource "nomad_job" "plugin_digitalocean_monolith" {
detach  = false
jobspec = file("${path.module}/../../jobs/plugin-digitalocean-monolith.nomad")
}
data "nomad_plugin" "digitalocean" {
depends_on   = [nomad_job.plugin_digitalocean_monolith]
plugin_id        = "digitalocean"
wait_for_registration = true
wait_for_healthy = true
}
resource "nomad_external_volume" "cortex" {
depends_on = [data.nomad_plugin.digitalocean]
count        = 1
type         = "csi"
plugin_id    = data.nomad_plugin.digitalocean.plugin_id
volume_id    = "cortex[${count.index}]"
name         = "cortex-${count.index}"
capacity_min = "1GiB"
capacity_max = "10GiB"
capability {
access_mode     = "single-node-writer"
attachment_mode = …
```
=> fix nomad_plugin not waiting for expectedControllers reported by nomad

nomad/datasource_nomad_plugin.go
Following up on #234, this PR reads the number of expected nodes from the API result and also blocks until all nodes are healthy.
=> Wait for CSI plugin nodes to be healthy

.github/workflows/test.yaml, scripts/getnomad.sh
The previous check would fail with this error:
```
./scripts/getnomad.sh: line 6: [: missing `]'
./scripts/getnomad.sh: line 6: -n: command not found
```
=> ci: fix nomad license env var check

nomad/resource_job.go, website/docs/r/job.html.markdown
There is an implicit cyclic dependency between providers when you try to use dynamic (i.e., generated by another provider) `vault_token` and `consul_token` in your Nomad provider configuration. This change introduces the ability to provide `vault_token` and `consul_token` as part of the `nomad_job` resource, so that dynamic token values can be provided by `vault` and `consul` providers respectively without hitting the [provider dependency issue](https://github.com/hashicorp/terraform/issues/2430).
Let me know how I can ensure the registry docs are also up to date with this change, and let me know if anything else is needed! Thanks!
=> feat: add vault and consul token to job resource

CHANGELOG.md, nomad/provider_test.go, nomad/resource_external_volume.go, nomad/resource_external_volume_test.go
Fixes https://github.com/hashicorp/terraform-provider-nomad/issues/260
The mount flags parsing tries to cast directly to a slice of strings,
but this silently fails and leaves us with empty mount flags.
---
I've tested this manually but I need to brush up on how to write Terraform tests because I don't quite understand how it's working in this repo. Putting the PR up for review while I work on that.
=> resource/external_volume: fix mount flags parsing

CHANGELOG.md, nomad/resource_volume.go
This fixes a bug where mount_flags were being silently dropped during resoruce creation.
I'm using Nomad v1.3.1 and terraform-provider-nomad v1.4.16.
I noticed that my `nomad_volume` `mount_options.mount_flags` weren't being set even though my `fs_type` **was** being set.
When creating the same volume directly with the `nomad` CLI mount_flags were being set so I knew it was a problem with the provider.
When the original error is not being ignored it causes a panic like so:
```
Stack trace from the terraform-provider-nomad_v1.4.16+dev plugin:
panic: interface conversion: interface {} is []interface {}, not []string
goroutine 55 [running]:
github.com/hashicorp/terraform-provider-nomad/nomad.resourceVolumeCreate(0xc00057f030, 0x1cbd860, 0xc00068c0c0, 0x24, 0x25a8540) …
```
=> resource(volume): fix parsing mount_flags

CHANGELOG.md, nomad/provider.go, website/docs/index.html.markdown
Allow users to opt-in into loading the NOMAD_NAMESPACE environment
variable. #271 removed this, as this was not intentional, but this value
is used in some workflows.
=> provider: add load_namespace_env_var configuration

CHANGELOG.md, nomad/provider.go, nomad/provider_test.go, website/docs/index.html.markdown
Add provider configuration option to allow users to ignore some
environment variables that would be otherwise loaded by default.
Read the `TFC_RUN_ID` environment variable to automatically ignore
`NOMAD_NAMESPACE` and `NOMAD_REGION`.
This re-implements #280 in a more re-usable way.
Closes #274
=> provider: add `ignore_env_vars` configuration

CHANGELOG.md, nomad/data_source_namespace.go, nomad/data_source_namespace_test.go, nomad/resource_namespace.go, nomad/resource_namespace_test.go, website/docs/d/namespace.html.markdown, website/docs/r/namespace.html.markdown
This PR adds the new blocks `meta` and `capabilities` for the namespace resource and data.
=> Add ns meta and capabilities

CHANGELOG.md, nomad/data_source_acl_role.go, nomad/data_source_acl_role_test.go, nomad/data_source_acl_roles.go, nomad/data_source_acl_roles_test.go, nomad/provider.go, nomad/resource_acl_role.go, nomad/resource_acl_role_test.go, website/docs/d/acl_role.html.markdown, website/docs/d/acl_roles.html.markdown, website/docs/r/acl_role.html.markdown
This change adds a new `nomad_acl_role` resource along with `nomad_acl_role` and `nomad_acl_roles` datasources.
In order to raise the change, the Nomad dependency has been updated to latest. This should be fixed to a release tag once 1.4.0 is released.
The tests do not currently run because the CI process requires a released version of Nomad :D. We can either merge this as is, or hold off until 1.4.0; but raising the PR now for early review.
=> acl: add ACL Role resource and data sources

CHANGELOG.md, nomad/provider.go, website/docs/index.html.markdown
Add `skip_verify` as an optional parameter to the schema to be able to skip TLS verification.
=> feat: add option to skip tls verfication

GNUmakefile, scripts/getconsul.sh, scripts/getnomad.sh, scripts/getvault.sh, scripts/start-nomad.sh, scripts/stop-nomad.sh
There are a few layered bugs that this fixes.
1.  When trying to capture the output of `scripts/start-nomad.sh`, the `shell` function never exits. I believe it's waiting on all processes spawned to exist, but we don't kill them until after the test. So the test execution was hanging. This was resolved by avoiding capture and instead reading the token from a file.
2. Apparently the shell function substitution doesn't happen sequentially within the target. When running the script and trying reading the variable using `$(shell cat /tmp/nomad-test.token)` right after, an error that `/tmp/nomad-test.token` doesn't exist is echoed before the script is even run. In order to ensure the script is run before trying to read the token, this is moved to a different target.
3. Output from the running …
=> Fix make localtestacc

CHANGELOG.md, nomad/data_source_variable.go, nomad/provider.go, nomad/resource_variable.go, nomad/resource_variable_test.go, website/docs/d/variable.html.markdown, website/docs/r/variable.html.markdown
This PR is based on #304. The original author, iluminae, of that PR is unable to continue their work.
Please note that I have not done Terraform provider work before, and very little Go work, so if some choices or questions don't make sense, that's probably why.
I have tried to implement the feedback that @lgfa29 had on the original PR. I did however only add a single test, I wanted to make sure I was on the write path before continuing.
=> Adding support for nomad variables

CHANGELOG.md, nomad/resource_acl_binding_rule.go, nomad/resource_acl_binding_rule_test.go, website/docs/r/acl_binding_rule.html.markdown
When creating a ACL binding rule, the bind name must not be defined but only when the bind_type is set to management.
https://developer.hashicorp.com/nomad/docs/commands/acl/binding-rule/create
Fixes #324
=> making bind_name optional when bind_type is management

.github/workflows/test.yaml, scripts/getconsul.sh, scripts/getnomad.sh, scripts/getvault.sh
I accidentally removed this line to set `NOMAD_TOKEN` to the runner environment in #326
https://github.com/hashicorp/terraform-provider-nomad/pull/326/commits/98e16b2ec4fca80a8f233e5f916dab980d725f8d#diff-a2adceb1476caa3f0076774cc3848b480976990a98d90b9fec9254a8a61a8bceL63
I also bumped Consul and Vault in that PR, but these newer enterprise versions require a license, but it turns out we don't actually need the ENT version of those tools in our tests, just Nomad.
=> ci: fix tests

CHANGELOG.md, nomad/resource_job.go, nomad/resource_job_test.go, website/docs/r/job.html.markdown
Parsing with HCL2 is the default behaviour of the Nomad CLI and so this change aims to make their behaviour the same.
The new `hcl1` attribute is provided for backwards compatibility to also match the Nomad CLI, which has the `-hcl1` flag.
=> resource/nomad_job: switch to HCL2 by default

CHANGELOG.md, nomad/resource_csi_volume.go, nomad/resource_csi_volume_registration.go, nomad/resource_external_volume.go, nomad/resource_volume.go
Fixes: https://github.com/hashicorp/terraform-provider-nomad/issues/338
The MR covers only `required` topology_request as that's what's implemented in the schema for this resource. Should it be extended to account also for `preferred`? According the the [Volume Specification](https://developer.hashicorp.com/nomad/docs/other-specifications/volume) they are both supported.
=> resource_volume : set topology_request on read

CHANGELOG.md, nomad/resource_csi_volume.go, nomad/resource_csi_volume_registration.go, nomad/resource_external_volume.go, nomad/resource_volume.go, website/docs/r/csi_volume.html.markdown, website/docs/r/csi_volume_registration.html.markdown, website/docs/r/external_volume.html.markdown, website/docs/r/volume.html.markdown
Add retry logic during volume create, register, deregister and delete.
Update deprecated resources since the deprecation has not happen yet, so keep them updated until v2.0.0 is out.
Closes https://github.com/hashicorp/terraform-provider-nomad/issues/335
=> volumes: add timeout and retry on create and delete

CHANGELOG.md, nomad/resource_job.go
When monitoring the job deployment and allocations the provider needs to set the job namespace in the request instead of relying on the provider configuration as it may be different from the job.
Closes https://github.com/hashicorp/terraform-provider-nomad/issues/300
=> resource/job: set namespace on monitor

nomad/data_source_node_pool_test.go, nomad/resource_csi_volume.go, nomad/resource_csi_volume_registration.go, nomad/resource_external_volume.go, nomad/resource_volume.go
Prevent errors of kind `Error: empty retryable error received.`
Sample error: https://github.com/hashicorp/terraform-provider-nomad/actions/runs/5600076107/job/15169538864#step:8:118
No changelog since this change has not been released.
=> volume: fix nil retryable error

CHANGELOG.md, nomad/resource_job.go
The previous implementation of the custom jobspec diff used a naive string equality check, which can result in unnecessary plan diffs due to inconsequential changes, like comments or spaces being added/removed.
By reusing the same logic as the `jobspec` field diff we compare the job struct as it would be submitted to the Nomad API.
Closes #349
Closes #290
=> resource/job: use semantic jobspec diff

CHANGELOG.md, nomad/resource_job.go, nomad/resource_job_test.go
Storing the list of allocation IDs in a `nomad_job` resource can lead to ever-changing plans since the list can change outsite of Terraform.
Retrieving this type of information is better suited for a data source.
The Terraform provider deprecation guide recommends attributes to be first marked as deprecated before full removal in the next major release.
Given that the next release will be a major release, this commit introduces a breaking change in behaviour (allocation IDs are not fetched by default anymore) but provides a fallback with the `read_allocation_ids` attribute.
Both attributes are marked as deprecated and will be removed in the next major release.
`nomad_allocations` data source added in https://github.com/hashicorp/terraform-provider-nomad/pull/358
=> resource/job: remove attribute allocation_ids

CHANGELOG.md, nomad/resource_csi_volume.go, nomad/resource_csi_volume_registration.go, nomad/resource_job.go
~No changelog since this is a new resource.~ 
Highjacking the PR to also add import support for jobs since I noticed that these are the last resources missing import.
Closes https://github.com/hashicorp/terraform-provider-nomad/issues/137
=> add import for CSI volumes and job

CHANGELOG.md, nomad/data_source_allocations.go, nomad/data_source_allocations_test.go, nomad/provider.go, website/docs/d/allocations.html.markdown
Add new data source to retrieve a list of allocations. Support prefix and filter to restrict results.
=> data source/allocations: add new data source

CHANGELOG.md, nomad/resource_csi_volume.go, nomad/resource_external_volume.go
Allow `capacity_min` and `capacity_max` to actually be optional values.
Closes https://github.com/hashicorp/terraform-provider-nomad/issues/362
=> volumes: fix capacity parsing to allow optional values

CHANGELOG.md, nomad/data_source_namespace.go, nomad/data_source_namespace_test.go, nomad/data_source_node_pool_test.go, nomad/resource_namespace.go, nomad/resource_namespace_test.go, nomad/resource_node_pool_test.go, scripts/getnomad.sh, website/docs/r/namespace.html.markdown
Add `node_pool_config` to `namespace` resource and data source.
Broken tests fixed in #354
Closes https://github.com/hashicorp/terraform-provider-nomad/issues/352
=> namespace: add node pool configuration

nomad/resource_job.go
The `enabled` value inside the `hcl2` block is deprecated and not used anywhere in the code and HCL2 parsing is the new default, so the schema default value should reflect that to avoid incorrect plan results.
Closes #368
=> job: fix HCL2 enabled default value

CHANGELOG.md, nomad/resource_external_volume.go, nomad/resource_volume.go
Revert retry logic added in #346 to avoid further issues with the existing volume resources (`nomad_external_volume` and `nomad_volume`). 
The new `nomad_csi_volume` and `nomad_csi_volume_registration` resources will have retries, but they require the use of the context CRUD methods (#371), which is a bigger change that we should not do for the deprecated resources.
=> volume: revert retry logic on deprecated volume

nomad/resource_variable.go
Unlike other methods, `client.Variables().Read()` returns a special error when the path queried doesn't exist. I wasn't able to validate all code paths, so I kept the explicit `404` check in place just in case.
This resource was also created before the SDKv2 upgrade, so some of the methods used were deprecated. This PR also updates them to use the new methods.
No changelog since this resource has not been released yet.
Closes #373
=> variable: fix 404 handling and remove deprecated methods

website/docs/r/acl_auth_method.html.markdown
This PR corrects the heading for the `nomad_acl_auth_method` resource on the docs page.
=> Docs: Corrected nomad_acl_auth_method docs page heading 

nomad/resource_acl_policy.go
the effect of this bug is that the job_acl namespace is always set to "default" regardless of input
=> fix typo bug in acl_policy resource for job_acl namespace field

.github/workflows/test.yaml
For some reason GitHub Actions started to get stuck on log update. I have not been able to debug exactly why, so just skipping this step for now.
=> ci: skip log upload on test

CHANGELOG.md, nomad/resource_csi_volume.go, nomad/resource_csi_volume_registration.go
Create `resourceCSIVolumeRegistrationImport`, and set some of the fields that terraform otherwise wants to re-create the registration over
Related to #390
=> Set fields when importing csi volume registrations

nomad/resource_job.go, nomad/resource_job_test.go
Refs #1. It's sometimes handy to use the UI to stop jobs e.g. during a maintenance event. In this specific case, the provider should check if the job is no longer running and resubmit it. I'm open to suggestions on how to approach this better.
=> job: ensure that job is running

CHANGELOG.md, nomad/resource_job.go
When register jobs by Http api need to set the job namespace in the request.
coder/coder#10074
=> resource/job: set namespace on register

CHANGELOG.md, nomad/resource_job.go, nomad/resource_job_test.go, website/docs/r/job.html.markdown
Follow-up work from https://github.com/hashicorp/terraform-provider-nomad/pull/389#pullrequestreview-1785043456 to introduce a new argument called `rerun_if_dead` to allow users to opt-in to the new behaviour.
=> job: add rerun_if_dead argument 

nomad/resource_csi_volume.go, nomad/resource_csi_volume_registration.go
CSI volumes have an external ID regardless on how they were added to Nomad, so add a computed attribute `external_id` to `nomad_csi_volume`.
This makes the schema of `nomad_csi_volume` and
`nomad_csi_volume_registration` compatible so that the read method can be shared between then again.
Alternate (and arguably correct 😅) implementation of https://github.com/hashicorp/terraform-provider-nomad/pull/402
=> volume: add computed attribute `external_id`

CHANGELOG.md, nomad/resource_job.go
The default behaviour of the Terraform SDK is to copy the plan result into state which could result in partial state updates, where Terraform state is updated, but the actual resource state is not, in case of an error during the apply.
This is normally not an issue because resources are expected to undo these changes on state refresh. Any partial update is reconciled with the actual resource state.
But due to #1, the `nomad_job` resource is not able to properly reconcile on refresh, causing the partial update to prevent further applies unless the configuration is also changed.
This commit uses the `d.Partial()` method to signal to Terraform that any state changes should be rolledback in case of an error.
Closes #385
=> job: prevent partial update on error

go.mod, go.sum
Pin `nomad/api` to https://github.com/hashicorp/nomad/commit/859606a54ade3fde43c2d89ed20a5e621ef2a53b so `service.cluster` is parsed properly.
=> deps: update `nomad/api` package

CHANGELOG.md, nomad/helper/import.go, nomad/resource_csi_volume.go, nomad/resource_csi_volume_registration.go, nomad/resource_job.go, website/docs/r/csi_volume.html.markdown, website/docs/r/csi_volume_registration.html.markdown, website/docs/r/job.html.markdown
`nomad_job`, `nomad_csi_volume`, and `nomad_csi_volume_registration` do not have the namespace as part of their state ID. This makes it impossible to import them if they are registered in a non-default namespace since only the ID is provided to the import function.
This commit adds a new helper that imports using an ID with the format `<id>@<namespace>`. Since `@` is not a valid character for namespaces, the last `@` character (if found) represents the separator.
Implements the approach suggested in https://github.com/hashicorp/terraform-provider-nomad/pull/375#issuecomment-1686797489.
=> job: import jobs from non-default namespace

CHANGELOG.md, nomad/resource_job.go, nomad/resource_job_test.go, website/docs/r/job.html.markdown
Send [job submission](https://developer.hashicorp.com/nomad/api-docs/jobs#submission) on register to retain original job source.
Closes #392
=> job: add job submission on register

website/docs/r/csi_volume_registration.html.markdown, website/docs/r/volume.html.markdown
The default value for these fields is `true`.
https://github.com/hashicorp/terraform-provider-nomad/blob/1c695fbd6eea13e17d864c38b223a36a1d426733/nomad/resource_volume.go#L235-L240
https://github.com/hashicorp/terraform-provider-nomad/blob/1c695fbd6eea13e17d864c38b223a36a1d426733/nomad/resource_csi_volume_registration.go#L245-L250
Closes https://github.com/hashicorp/terraform-provider-nomad/issues/416.
=> docs: fix default value of `deregister_on_destroy`

website/docs/d/job.html.markdown
When reading a job using the `nomad_job` datasource it is possible to pass a `namespace` argument to specify the namespace to be used when reading the job information.
Closes https://github.com/hashicorp/terraform-provider-nomad/issues/426
=> docs: fix `data.nomad_job` namespace argument

scripts/getnomad.sh
Fix CI by updating the Nomad version installed.
https://github.com/hashicorp/terraform-provider-nomad/pull/429 added support to a feature that is only available on Nomad 1.7.3+. I'm not sure why CI didn't run in that PR 🤷
=> ci: update Nomad version used in tests

CHANGELOG.md, nomad/resource_acl_auth_method.go, website/docs/r/acl_auth_method.html.markdown
Set the token name default value used by Nomad to avoid unnecessary plan changes when the attribute is not defined.
Reported in https://github.com/hashicorp/terraform-provider-nomad/pull/403#issuecomment-1960136907
=> acl_auth_method: fix token name format default

nomad/resource_variable_test.go
Establish implicit dependency between the variable and the new namespace so they are destroyed in the right order.
Closes #440
=> test: fix `TestResourceVariable_namespaceChange`

CHANGELOG.md, nomad/resource_acl_auth_method.go, website/docs/r/acl_auth_method.html.markdown
=> Add JWT options for acl_auth_method

CHANGELOG.md, nomad/data_source_jwks.go, nomad/data_source_jwks_test.go, nomad/provider.go, website/docs/d/jwks.html.markdown
This adds a `data` provider for the JWKS public keys used for verifying workload identity JWTs. These are exposed at the `/.well-known/jwks.json` HTTP API endpoint.
One use for this would be to provide these keys to Vault via https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/jwt_auth_backend#jwt_validation_pubkeys. This would be useful, because Vault cannot access the HTTPS API with mTLS enabled unless one turns off client verification: https://developer.hashicorp.com/nomad/docs/integrations/vault/acl#mutual-tls-in-nomad
The keys are returned as both a list of objects with human-readable field names, and as a list of PEM-encoded X.509 public keys; the latter is, I believe, the preferred way to pass PKI information in Terraform, and is the format that the …
=> Add JWKS data source for fetching public keys for JWT validation

scripts/start-nomad.sh
Fixes CI errors such as the one seen here: https://github.com/hashicorp/terraform-provider-nomad/actions/runs/9535034665/job/26299008859
=> ci: use latest version of Nomad's hostpath jobfile.

nomad/resource_job_test.go, nomad/resource_namespace.go, nomad/resource_namespace_test.go, nomad/resource_quota_specification.go, scripts/getnomad.sh
Nomad 1.8.2 will [no longer allow](https://github.com/hashicorp/nomad/pull/23499) for deleting of quota specs if they are associated with a namespace. Namespace deletion will now also detect non-terminal allocations, so we have to support retries when deleting these. 
Fixes https://github.com/hashicorp/nomad/issues/23672
Internal ref: https://hashicorp.atlassian.net/browse/NET-10579
_note to reviewers:_ this PR also bumps the version of Nomad used for unit tests to 1.8.2. I will make a follow-up PR that installs nomad with hc-install so that we can assure we're always running tests against latest stable.
=> namespaces: handle quota spec disassociation and non-terminal allocations

nomad/data_source_namespaces_test.go, nomad/datasource_nomad_job_test.go, nomad/provider_test.go, nomad/resource_job_test.go, nomad/resource_namespace_test.go
Namespaces were moved from Enterprise to CE some time ago, but it appears that some of the tests for the provider never had their ENT-only gate removed so they're not being run on CE. One test for scheduler configuration was missing an ENT-only gate as well.
Additionally, missing `t.Helper()` flags were causing these skips to be reported as if they were version number check failures, which was confusing. This changeset fixes that and simplifies the test helper for version checks so the helper function that gets the version from the node returns a value rather than taking a callback, and uses the `Core` method on the checked version to allow easier development against new features on Nomad's main branch.
=> testing: reduce skipped checks for non-enterprise builds

website/docs/r/acl_policy.html.markdown
Workload-associated ACL policies can only be set on a specific job within a namespace, not the namespace as a whole. Clarify the documentation of the provider.
Fixes: https://github.com/hashicorp/terraform-provider-nomad/issues/500
Ref: https://github.com/hashicorp/nomad/pull/24882
Ref: https://hashicorp.atlassian.net/browse/NET-11994
=> docs: clarify workload-associated policy parameters

nomad/resource_csi_volume.go, website/docs/r/csi_volume.html.markdown
The `context` output is missing from `resource.nomad_csi_volume`. This prevents successfully migrating from the deprecated `resource.nomad_external_volume`. Add it as a computed value that we get from the plugins.
Fixes: https://github.com/hashicorp/terraform-provider-nomad/issues/494
Fixes: https://github.com/hashicorp/terraform-provider-nomad/issues/417
Ref: https://hashicorp.atlassian.net/browse/NET-11851
---
Tested using the most recent available Docker release of [democratic-csi](https://github.com/democratic-csi/democratic-csi) (v1.9.3, not sure why the version shows as 1.9.0 below).
```
$ nomad plugin status org.democratic-csi.nfs
ID                   = org.democratic-csi.nfs
Provider             = org.democratic-csi.nfs
Version              = 1.9.0
Controllers Healthy  = 1 …
```
=> add context argument to resource.nomad_csi_volume

nomad/provider_test.go
Ent feature tests have been getting skipped. At first I thought it was due to CI not downloading an ent binary, but no it turns out that this one line is stripping the `+ent` metadata from the version.
I don't know why `.Core()` was put here initially, but it smells like it might have been vestigial after some reworking in 0cab885b832dd9ddd43594d953fd3605cabe6904 -- one caller calls `.Core()` on the _result_ of this `testGetVersion()` func to compare against min version.
The tests do still pass (on my laptop) when run without an ent binary, too.
=> run ent tests on ent clusters

CHANGELOG.md, nomad/resource_dynamic_host_volume.go, nomad/resource_dynamic_host_volume_registration.go, nomad/resource_dynamic_host_volume_registration_test.go, nomad/resource_dynamic_host_volume_test.go, website/docs/r/dynamic_host_volume.html.markdown, website/docs/r/dynamic_host_volume_registration.html.markdown
When importing a dynamic host volume resource, the provider was missing the resource importer helper we use to pass in IDs like `$uuid@$namespace`. Add this to the importer and the docs.
Fixes: https://github.com/hashicorp/terraform-provider-nomad/issues/550
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
=> DHV: add namespace handling to import

go.mod, go.sum
When we updated the Nomad package in 2.5.1, we forgot to update the Nomad API package as well, so using features like `template.once` are not working.
Fixes: https://github.com/hashicorp/terraform-provider-nomad/issues/548
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
=> deps: update Nomad Go API package
