- README.md
- nomad/provider.go
- nomad/provider_test.go
- nomad/resource_job_test.go
- vendor/github.com/hashicorp/nomad/api/acl.go
- vendor/github.com/hashicorp/nomad/api/agent.go
- vendor/github.com/hashicorp/nomad/api/allocations.go
- vendor/github.com/hashicorp/nomad/api/api.go
- vendor/github.com/hashicorp/nomad/api/contexts/contexts.go
- vendor/github.com/hashicorp/nomad/api/deployments.go
- vendor/github.com/hashicorp/nomad/api/evaluations.go
- vendor/github.com/hashicorp/nomad/api/fs.go
- vendor/github.com/hashicorp/nomad/api/jobs.go
- vendor/github.com/hashicorp/nomad/api/jobs_testing.go
- vendor/github.com/hashicorp/nomad/api/namespace.go
- vendor/github.com/hashicorp/nomad/api/nodes.go
- vendor/github.com/hashicorp/nomad/api/operator.go
- vendor/github.com/hashicorp/nomad/api/quota.go
- vendor/github.com/hashicorp/nomad/api/search.go
- vendor/github.com/hashicorp/nomad/api/sentinel.go
- vendor/github.com/hashicorp/nomad/api/system.go
- vendor/github.com/hashicorp/nomad/api/tasks.go
- vendor/github.com/hashicorp/nomad/helper/uuid/uuid.go
- vendor/github.com/hashicorp/nomad/helper/uuid/uuid_test.go
- vendor/vendor.json
Just update #17 to remove some of the stuff, so they don't have to wait on back-and-forth and can get something merged quickly.
> Clean up #17

- website/docs/index.html.markdown
Add the new secret_id field on the provider.
> Document the new field.

- CHANGELOG.md
> updated CHANGELOG to reflect new PRs

- nomad/data_source_namespaces_test.go
- nomad/provider_test.go
- nomad/resource_job_test.go
- nomad/resource_namespace_test.go
- nomad/resource_quota_specification_test.go
- nomad/resource_sentinel_policy_test.go
gate tests based on whether targeted nomad is oss/pro/ent and whether vault is enabled
> gate tests based on capability 

- nomad/data_source_deployments_test.go
Existing checks would always pass as deployments endpoint did not error but returned an empty list, it also did not have an update stanza and thus would not even register a deployment. Test now creates resource, checks deployments, destroys and checks for cancelled deployment. It isn't the greatest use of the test harness but it works, I could not find any other way through it (depends_on does not work well in datasources https://www.terraform.io/docs/configuration/data-sources.html#data-resource-dependencies)
Should unblock #55
> Fix datasource deployments tests

- website/docs/r/acl_policy.html.markdown
- website/docs/r/acl_token.html.markdown
- website/docs/r/namespace.html.markdown
- website/docs/r/sentinel_policy.html.markdown
- It's easier on the eyes if everything is lined up, and this makes all
of the existing docs consistent.
> Run `terraform fmt` over the example code in the docs

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
Add Nomad specific questions and migrate to new GitHub issue template.
> Update issue templates

- nomad/resource_acl_token.go
- nomad/resource_acl_token_test.go
- website/docs/r/acl_token.html.markdown
Fixes terraform-providers/terraform-provider-nomad#84
> Add `create_time` computed value to `nomad_acl_token` resource

- nomad/data_source_acl_token.go
- nomad/data_source_acl_token_test.go
- nomad/provider.go
- website/docs/d/acl_token.html.markdown
- website/nomad.erb
This PR adds the data source for ACL tokens resource.
closes #85
> add data source for nomad ACL tokens

- website/docs/r/acl_policy.html.markdown
- adds 0.12 example
- adds 0.11 example
- fixes grammar (a/an)
> updates rules_hcl interpolation for 0.12

- nomad/data_source_namespace.go
- nomad/data_source_namespace_test.go
- nomad/provider.go
- website/docs/d/namespace.html.markdown
- website/nomad.erb
Closes https://github.com/terraform-providers/terraform-provider-nomad/issues/87
> Add nomad_namespace data source

- CHANGELOG.md
> changelog entries

- nomad/data_source_acl_tokens.go
- nomad/data_source_acl_tokens_test.go
- nomad/provider.go
- website/docs/d/acl_tokens.html.markdown
- website/nomad.erb
Closes https://github.com/terraform-providers/terraform-provider-nomad/issues/86
> Add nomad_acl_tokens data source

- CHANGELOG.md
- nomad/data_source_acl_policy_test.go
- nomad/data_source_job_parser.go
- nomad/data_source_job_parser_test.go
- nomad/provider.go
- website/docs/d/job_parser.html.markdown
- website/nomad.erb
Add new data source for job parser as well as relevant tests & documentation. 
Paired with Luiz for coding so tagging others in to review.
> data-source/job_parser: add new data source

- CHANGELOG.md
- go.mod
- go.sum
- nomad/core/jobspec/parse.go
- nomad/core/jobspec/parse_service.go
- nomad/data_source_job_parser_test.go
- nomad/resource_job_test.go
- scripts/getnomad.sh
> Update Nomad dependency to v0.12.2

- CHANGELOG.md
- nomad/provider.go
- nomad/provider_test.go
- nomad/resource_job.go
- nomad/resource_job_test.go
- website/docs/index.html.markdown
> support injecting consul token into job

- nomad/provider_test.go
- nomad/resource_job_test.go
- scripts/getnomad.sh
Also skip TestResourceJob_consulConnect() if Consul is not running.
> Don't require a Nomad license to run GitHub Actions

- website/docs/r/job.html.markdown
> website: add note about HCL2 and new jobspec blocks

- nomad/resource_scheduler_config.go
- nomad/resource_scheduler_config_test.go
Closes #258 
If there's a more elegant way to write the test, lmk
> Set memory_oversubscription_enabled in resourceSchedulerConfigurationRead

- website/docs/r/job.html.markdown
When using HCL2 variables in job files it's not possible to provide their values by reading the output of resources that don't exist in the state yet. Since Terraform doesn't know their value it will always send an empty `vars` map to the Nomad provider.
Document the problem and provide guidance and workarounds.
Closes #257
> docs: document issues with HCL2 vars and resource outputs

- website/docs/r/scheduler_config.html.markdown
mention memory_oversubscription_enabled in the example
> mention `memory_oversubscription_enabled`

- website/docs/r/job.html.markdown
> fix: typo in doc

- .github/workflows/release.yml
- .github/workflows/test.yaml
> build: remove deprecated set-output command from GHA

- CHANGELOG.md
- nomad/data_source_volumes.go
> data source/nomad_volume: fix panic when reading volume.

- nomad/resource_csi_volume.go
- nomad/resource_csi_volume_registration.go
Upddate `nomad_csi_volume` and `nomad_csi_volume_registration` to use CRUD methods with context and allow retries to be cancelled.
The read method was not updated because the signature clashes with the RetryContextFunc and there is not a nice way to transform a `diag.Diagnostics` to an `error`.
No changelog since these are unreleased resources.
Closes #367
> volume: use context methods

- CHANGELOG.md
- go.mod
- go.sum
- nomad/resource_acl_auth_method.go
- nomad/resource_acl_auth_method_test.go
- website/docs/r/acl_binding_rule.html.markdown
In nomad 1.7.3 a new config has been [introduced](https://github.com/hashicorp/nomad/pull/19566) Adding support for this config parameter
> Adding support for OIDCDisableUserInfo

- CHANGELOG.md
Jira: https://hashicorp.atlassian.net/jira/software/c/projects/NET/issues/NET-11323
> release: update changelog to mark 2.4.0 release.

- nomad/data_source_allocations_test.go
The acceptance test for `data.nomad_allocations` creates a job and then reads the allocations in the same configuration. This results in frequent test flakes because registering a job via `resource.nomad_job` will typically return before the allocations have actually been created, making the `depends_on` useless.
This frankly isn't a good workflow to encourage, as allocations are ephemeral. But fix the test by creating the job first, waiting for the allocations to be live, and then adding the `data.nomad_allocations` object to the config.
> testing: fix test flake in data.nomad_allocations test

- CHANGELOG.md
Forgot to do this in #523 and #524
> changelog: add new oidc features

- CHANGELOG.md
Prepares changelog for next release
> prepare for next release

- CHANGELOG.md
> changelog typo: 's'es are lippery

- .release/ci.hcl
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
> fix: add missing closing bracket
